### ISSUE TITLE
Deploy the webapp in Heroku or Repl.it

### ISSUE THREAD

**Issue by arkochatterjee** [thinking-tomorrow/Covid19#6]

**Comment by sajjad006** [comment]
@arkochatterjee it's deployed on pythonanywhere (http://covidinfo.pythonanywhere.com/). But there is a problem. We are scraping the data from [worldometer.info/coronavirus](https://worldometer.info/coronavirus) but pythonanywhere does not allow to request third party websites and scrape data (unless they have a documented API). So although the site functions but majority of our features are not available because we heavily rely upon that data. 

We are trying to deploy it on Heroku but facing some trouble. We'll try to resolve it ASAP. Any help is welcome.

![image](https://user-images.githubusercontent.com/62112142/81934254-4afba080-960c-11ea-9a1e-66f2bfb22b2a.png)

**Comment by Hrishikesh-coder** [comment]
@arkochatterjee It would be great if u could help us .

**Comment by arkochatterjee** [comment]
Let's settle this via mail!

**Comment by Hrishikesh-coder** [comment]
@arkochatterjee We have hosted this website now on aws and it is working absolutely fine .
You may have a look at the website at : ncov19info.tk .
Thanks for all the help !!
